dist: trusty
sudo: required
language: node_js
node_js:
  - "6"

notifications:
  email: false

env:
  - SCRIPT=lint
  - SCRIPT=slint
  - SCRIPT=e2e
  # TODO: needs solution for router testing in template
  # - SCRIPT=test

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export CHROME_BIN=chromium-browser
  - npm config set spin false
  - npm config set progress false

install:
  - npm install --no-optional

before_script:
  - if [[ "$SCRIPT" == "e2e" ]]; then npm start & sleep 20 fi

script:
  - npm run $SCRIPT
